title: History of Video Game Consoles
baseurl: ""
url: "http://interactivegamemuseum.com/"

profilepic: 
bkimage: /images/bk.jpg

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
