title: History of Video Game Consoles
baseurl: ''  
url: 'https://interactivegamemuseum.com'  

profilepic: /images/mark.jpg
bkimage: /images/bk.jpg

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
